name:                def
version:             0.2.0.1
github:              "foshardware/def"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"
build-type:          Custom


extra-source-files:
- README.md
- ChangeLog.md

custom-setup:
  dependencies:
  - base >= 4.7 && < 5
  - Cabal
  - process

description:         Please see the README on GitHub at <https://github.com/foshardware/def#readme>

dependencies:
- base >= 4.7 && < 5
- array
- filepath
- parsec
- tasty
- tasty-hunit
- tasty-quickcheck
- text
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

tests:
  def-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -O
    - -threaded
    - -rtsopts
    dependencies:
    - def
